version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:dev-${DOCKER_IMAGE_VERSION}
    container_name: urban-breeze-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    networks:
      - prod-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  prod-network: