version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:dev-${DOCKER_IMAGE_VERSION}
    environment:
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
