services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:prod-${DOCKER_IMAGE_VERSION}
    container_name: urban-breeze-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - /var/log/urbanbreeze:/app/logs
    networks:
      - prod-network
    restart: unless-stopped

networks:
  prod-network:
    driver: bridge