name: Deploy prod to AWS EC2

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Timezone to Asia/Seoul
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Seoul"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Setup application.yml (PROD)
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application.yml

      - name: Build Spring Project
        run: ./gradlew clean bootJar

      - name: Get current datetime
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build & Push (prod)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile            # ← prod용 Dockerfile (dev면 Dockerfile.dev)
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:prod-${{ steps.datetime.outputs.datetime }}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:prod-latest
          build-args: JAR_FILE=build/libs/app.jar

      - name: Upload docker-compose.prod.yml
        uses: actions/upload-artifact@v4
        with:
          name: compose-yml
          path: ./docker-compose.prod.yml

    outputs:
      BUILD_VERSION: ${{ steps.datetime.outputs.datetime }}

  deploy:
    runs-on: [self-hosted, app-prod]      # ← prod 전용 러너 라벨
    needs: build
    environment:
      name: production                     # ← GitHub Environments 사용 시 승인/비밀변수 분리 가능

    steps:
      - name: Download docker-compose.prod.yml
        uses: actions/download-artifact@v4
        with:
          name: compose-yml
          path: .

      - name: Write .env (prod)
        run: |
          cat <<EOF > .env
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          DOCKER_REPO=${{ secrets.DOCKER_REPO }}
          DOCKER_IMAGE_VERSION=${{ needs.build.outputs.BUILD_VERSION }}
          EOF

      - name: Stop OLD prod app container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^urban-breeze-prod$'; then
            sudo docker stop urban-breeze-prod
            sudo docker rm urban-breeze-prod
          fi

      - name: Prune Docker Images
        run: sudo docker image prune -a -f

      - name: Run New Containers (prod)
        run: sudo docker compose -f docker-compose.prod.yml up -d